package types

const (
	NUMBER     = "number"
	STRING     = "string"
	BUILTIN    = "builtin"
	META       = "meta"
	IDENTIFIER = "identifier"
	EOL        = "new line"
	EOF        = "end of file"
	IF         = "if"
	ELIF       = "elif"
	ELSE       = "else"
	FOR        = "for"
	BREAK      = "break"
	CONTINUE   = "continue"
	SWITCH     = "switch"
	CASE       = "case"
	FN         = "fn"
	RETURN     = "return"
	IMPORT     = "import"
	THROW      = "throw"
	TRUE       = "true"
	FALSE      = "false"
	NIL        = "nil"
	EQEQ       = "=="
	EQ         = "="
	NOTEQ      = "!="
	NOT        = "!"
	PLUSEQ     = "+="
	PLUSPLUS   = "++"
	PLUS       = "+"
	MINUSEQ    = "-="
	MINUSMINUS = "--"
	MINUS      = "-"
	MULTIPLYEQ = "*="
	MULTIPLY   = "*"
	DIVIDEEQ   = "/="
	DIVIDE     = "/"
	MODULOEQ   = "%="
	MODULO     = "%"
	ANDAND     = "&&"
	AND        = "&"
	OROR       = "||"
	OR         = "|"
	XOR        = "^"
	BNOT       = "~"
	LTEQ       = "<="
	LTLT       = "<<"
	LT         = "<"
	GTEQ       = ">="
	GTGT       = ">>"
	GT         = ">"
	COLONEQ    = ":="
	COLONCOLON = "::"
	COLON      = ":"
	DOT        = "."
	COMMA      = ","
	LPAREN     = "("
	RPAREN     = ")"
	LBRACE     = "{"
	RBRACE     = "}"
	LBRACKET   = "["
	RBRACKET   = "]"
	QM         = "?"
)
