// SPDX-License-Identifier: GPL-3.0-or-later
package types

const (
	INT        = "integer"
	FLOAT      = "float"
	STRING     = "string"
	BUILTIN    = "builtin"
	IDENT      = "identifier"
	EOL        = "new line"
	EOF        = "end of file"
	TRUE       = "true"
	FALSE      = "false"
	ANDAND     = "and"
	OROR       = "or"
	IF         = "if"
	ELIF       = "elif"
	ELSE       = "else"
	SWITCH     = "switch"
	CASE       = "case"
	LOOP       = "loop"
	FN         = "fn"
	RETURN     = "return"
	IMPORT     = "import"
	THROW      = "throw"
	TRY        = "try"
	CATCH      = "catch"
	FINALLY    = "finally"
	EQEQ       = "=="
	EQ         = "="
	NOTEQ      = "!="
	NOT        = "!"
	PLUSEQ     = "+="
	PLUS       = "+"
	MINUSEQ    = "-="
	MINUS      = "-"
	MULTIPLYEQ = "*="
	MULTIPLY   = "*"
	DIVIDEEQ   = "/="
	DIVIDE     = "/"
	MODULOEQ   = "%="
	MODULO     = "%"
	AND        = "&"
	OR         = "|"
	XOR        = "^"
	BNOT       = "~"
	LTEQ       = "<="
	LTLT       = "<<"
	LT         = "<"
	GTEQ       = ">="
	GTGT       = ">>"
	GT         = ">"
	COLONEQ    = ":="
	COLONCOLON = "::"
	COLON      = ":"
	DOT        = "."
	COMMA      = ","
	LPAREN     = "("
	RPAREN     = ")"
	LBRACE     = "{"
	RBRACE     = "}"
	LBRACKET   = "["
	RBRACKET   = "]"
	QM         = "?"
)
